public with sharing class SimpleDML1 {
    public SimpleDML1() {

    }

    // Build out the following method to do the following:
    // 
    // - Create a new account and add an opportunity for it
    //
    // - Change the name of the Opportunity to the record ID
    //
    // - Return the Id of the new Account record
    //
    // Do not use any SOQL statements
    public Id CreateAccountAndOpportunity()
    {
        return null;
    }
}
